CREATE TABLE lc_demo_documents (
    doc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR2(512) NOT NULL,
    document_text CLOB NOT NULL,
    document_type VARCHAR2(128) NOT NULL,
    source_file VARCHAR2(128),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_lc_demo_documents_name UNIQUE (document_name)
);

CREATE TABLE lc_demo_chunks (
    doc_id NUMBER NOT NULL,
    chunk_id NUMBER NOT NULL,
    chunk_tokens NUMBER NOT NULL,
    chunk_text CLOB NOT NULL,
    embedding VECTOR(2048, FLOAT32) NOT NULL,
    document_type VARCHAR2(128) NOT NULL,
    source_file VARCHAR2(128),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_lc_demo_chunks PRIMARY KEY (doc_id, chunk_id),
    CONSTRAINT fk_lc_demo_chunks_doc
        FOREIGN KEY (doc_id)
        REFERENCES lc_demo_documents (doc_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_lc_demo_chunks_source
        CHECK ((chunk_id = 1 AND source_file IS NOT NULL) OR (chunk_id > 1 AND source_file IS NULL))
);

CREATE INDEX lc_demo_chunks_doc_type_ix
    ON lc_demo_chunks (document_type);
